import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/pages/Layout/Header";
import Footer from "@/components/pages/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" sticky top-0 z-50 bg-white">
          <Header />
        </div>
        {children}
        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
